# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTML_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('time_taken', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HTML Record',
            },
        ),
        migrations.CreateModel(
            name='IP_Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('isp', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'IP Record',
            },
        ),
        migrations.CreateModel(
            name='URL_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('connections', models.ManyToManyField(to='miner.URL_Log')),
                ('ip', models.ManyToManyField(related_name='urls', to='miner.IP_Geo')),
            ],
            options={
                'verbose_name': 'URL Record',
            },
        ),
        migrations.AddField(
            model_name='html_log',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html', to='miner.URL_Log'),
        ),
        migrations.AddField(
            model_name='html_log',
            name='urls',
            field=models.ManyToManyField(related_name='appears_in', to='miner.URL_Log'),
        ),
    ]
