# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.GenericIPAddressField()),
                ('to_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
